In [1]:
import pandas as pd
import numpy as np

In [2]:
import unicodedata
def strip_accents(s):
   return ''.join(c for c in unicodedata.normalize('NFD', s)
                  if unicodedata.category(c) != 'Mn')

In [3]:
data = pd.read_csv("All_data_limpia.csv")

/usr/local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (9,12,13,16,21,28,32,33,34,35,36,37,40,41,42,43,44,45,46,49) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
data.columns

Index(['Column', 'Calle', 'Causa', 'Ciudad', 'Cruce', 'Fecha', 'Hora', 'ID',
       'Latitud', 'Lesionados', 'Longitud', 'Mes', 'Muertos',
       'No. De Infracción', 'Número  total de lesionados',
       'Número total de muertos', 'Por alcohol', 'Sentido',
       'Situación climática', 'Situación del Pavimento', 'Tipo de incidente',
       'Tipo de involucrado', 'Tipo de vía', 'V1_Arresto', 'V1_Dictamen',
       'V1_Edad', 'V1_Estatus Licencia', 'V1_Género', 'V1_No. De Fallecidos',
       'V1_No. De Lesionados', 'V1_Tipo de Vehículo', 'V1_Uso de Cinturón',
       'V2_Arresto', 'V2_Dictamen', 'V2_Edad', 'V2_Estatus Licencia',
       'V2_Género', 'V2_No. De Fallecidos', 'V2_No. De Lesionados',
       'V2_Tipo de Vehículo', 'V2_Uso de Cinturón', 'V3_Arresto',
       'V3_Dictamen', 'V3_Edad', 'V3_Estatus Licencia', 'V3_Género',
       'V3_No. De Fallecidos', 'V3_No. De Lesionados', 'V3_Tipo de Vehículo',
       'V3_Uso de Cinturón'],
      dtype='object')

In [5]:
data["Mes"] = data["Mes"].str.lower()

In [6]:
data["Mes"].value_counts()

marzo         6149
febrero       5508
agosto        5457
mayo          5345
junio         5183
abril         5129
septiembre    4842
octubre       4449
julio         4361
noviembre     3150
diciembre     3061
enero         2274
Name: Mes, dtype: int64

In [7]:
data["Ciudad"] = data["Ciudad"].str.lower()
data["Ciudad"] = data["Ciudad"].str.strip()
data["Ciudad"] = data["Ciudad"].map(lambda x: strip_accents(str(x)))
data["Ciudad"].value_counts()

monterrey         20961
san pedro          8242
san nicolas        6953
apodaca            4269
garcia             4046
guadalupe          3893
santa catarina     3595
escobedo           3049
nan                   4
                      1
Name: Ciudad, dtype: int64

In [8]:
for i in range(0,len(data["Fecha"]), 100):
    print(data["Fecha"][i])
    print(i)

2016-05-01 00:00:00
0
2016-05-02 00:00:00
100
2016-05-04 00:00:00
200
2016-05-05 00:00:00
300
2016-05-06 00:00:00
400
2016-05-08 00:00:00
500
2016-05-09 00:00:00
600
2016-05-10 00:00:00
700
2016-05-11 00:00:00
800
2016-05-13 00:00:00
900
2016-05-14 00:00:00
1000
2016-05-15 00:00:00
1100
2016-05-17 00:00:00
1200
2016-05-18 00:00:00
1300
2016-05-19 00:00:00
1400
2016-05-20 00:00:00
1500
2016-05-21 00:00:00
1600
2016-05-23 00:00:00
1700
2016-05-24 00:00:00
1800
2016-05-26 00:00:00
1900
2016-05-27 00:00:00
2000
2016-05-29 00:00:00
2100
2016-05-30 00:00:00
2200
2016-06-01 00:00:00
2300
2016-06-02 00:00:00
2400
2016-06-03 00:00:00
2500
2016-06-04 00:00:00
2600
2016-06-06 00:00:00
2700
2016-06-07 00:00:00
2800
2016-06-09 00:00:00
2900
2016-06-10 00:00:00
3000
2016-06-11 00:00:00
3100
2016-06-13 00:00:00
3200
2016-06-13 00:00:00
3300
2016-06-15 00:00:00
3400
2016-06-16 00:00:00
3500
2016-06-17 00:00:00
3600
2016-06-18 00:00:00
3700
2016-06-20 00:00:00
3800
2016-06-21 00:00:00
3900
2016-06-22 00:00:00
4000
2016-06-23 00:00:00
4100
2016-06-24 00:00:00
4200
2016-06-25 00:00:00
4300
2016-06-27 00:00:00
4400
2016-06-28 00:00:00
4500
2016-06-30 00:00:00
4600
2016-07-01 00:00:00
4700
2016-07-02 00:00:00
4800
2016-07-03 00:00:00
4900
2016-07-05 00:00:00
5000
2016-07-06 00:00:00
5100
2016-07-07 00:00:00
5200
2016-07-08 00:00:00
5300
2016-07-10 00:00:00
5400
2016-07-11 00:00:00
5500
2016-07-13 00:00:00
5600
2016-07-14 00:00:00
5700
2016-07-15 00:00:00
5800
2016-07-17 00:00:00
5900
2016-07-18 00:00:00
6000
2016-07-20 00:00:00
6100
2016-07-22 00:00:00
6200
2016-07-23 00:00:00
6300
2016-07-25 00:00:00
6400
2016-07-26 00:00:00
6500
2016-07-28 00:00:00
6600
2016-07-29 00:00:00
6700
2016-07-31 00:00:00
6800
2016-05-03 00:00:00
6900
2016-05-07 00:00:00
7000
2016-05-10 00:00:00
7100
2016-05-13 00:00:00
7200
2016-05-17 00:00:00
7300
2016-05-20 00:00:00
7400
2016-05-24 00:00:00
7500
2016-05-27 00:00:00
7600
2016-06-01 00:00:00
7700
2016-06-04 00:00:00
7800
2016-06-11 00:00:00
7900
2016-06-14 00:00:00
8000
2016-06-18 00:00:00
8100
2016-06-25 00:00:00
8200
2016-07-21 00:00:00
8300
2016-05-07 00:00:00
8400
2016-05-15 00:00:00
8500
2016-05-24 00:00:00
8600
2016-06-01 00:00:00
8700
2016-06-09 00:00:00
8800
2016-06-15 00:00:00
8900
2016-06-21 00:00:00
9000
2016-06-28 00:00:00
9100
2016-07-04 00:00:00
9200
2016-07-09 00:00:00
9300
2016-07-17 00:00:00
9400
2016-05-21 00:00:00
9500
2016-06-04 00:00:00
9600
2016-06-18 00:00:00
9700
2016-06-30 00:00:00
9800
2016-07-07 00:00:00
9900
2016-07-13 00:00:00
10000
2016-07-17 00:00:00
10100
2016-07-23 00:00:00
10200
2016-07-29 00:00:00
10300
2016-05-08 00:00:00
10400
2016-06-19 00:00:00
10500
2016-07-05 00:00:00
10600
2016-07-03 00:00:00
10700
2016-06-09 00:00:00
10800
2016-06-30 00:00:00
10900
2016-07-25 00:00:00
11000
2016-05-03 00:00:00
11100
2016-05-08 00:00:00
11200
2016-05-20 00:00:00
11300
2016-05-31 00:00:00
11400
2016-06-10 00:00:00
11500
2016-06-24 00:00:00
11600
2016-07-03 00:00:00
11700
2016-07-11 00:00:00
11800
2016-07-21 00:00:00
11900
03/05/2016 05:31:00 p.m.
12000
07/05/2016 10:26:00 p.m.
12100
11/05/2016 02:09:00 p.m.
12200
16/05/2016 11:24:00 a.m.
12300
19/05/2016 01:20:00 a.m.
12400
23/05/2016 06:51:00 p.m.
12500
27/05/2016 08:38:00 a.m.
12600
31/05/2016 07:19:00 p.m.
12700
04/06/2016 09:42:00 a.m.
12800
09/06/2016 10:15:00 a.m.
12900
14/06/2016 05:37:00 p.m.
13000
18/06/2016 03:32:00 p.m.
13100
23/06/2016 10:51:00 p.m.
13200
30/06/2016 12:52:00 a.m.
13300
05/07/2016 01:24:00 p.m.
13400
11/07/2016 11:45:00 a.m.
13500
16/07/2016 11:32:00 p.m.
13600
21/07/2016 07:32:00 a.m.
13700
26/07/2016 06:22:00 p.m.
13800
2016-07-22 00:00:00
13900
2016-07-30 00:00:00
14000
2016-05-15 00:00:00
14100
2016-05-23 00:00:00
14200
2016-05-30 00:00:00
14300
2016-06-06 00:00:00
14400
2000-06-13 00:00:00
14500
2016-06-20 00:00:00
14600
2006-06-26 00:00:00
14700
2016-07-02 00:00:00
14800
2016-07-08 00:00:00
14900
2016-07-16 00:00:00
15000
2016-08-07 00:00:00
15100
2016-08-14 00:00:00
15200
2016-08-21 00:00:00
15300
2016-08-28 00:00:00
15400
2016-09-04 00:00:00
15500
2016-09-14 00:00:00
15600
2016-09-25 00:00:00
15700
2016-10-05 00:00:00
15800
2016-10-13 00:00:00
15900
2016-10-20 00:00:00
16000
2016-10-09 00:00:00
16100
2016-10-19 00:00:00
16200
2016-10-28 00:00:00
16300
06/08/2016
16400
2016-08-12 00:00:00
16500
2016-08-20 00:00:00
16600
2016-09-02 00:00:00
16700
2016-09-15 00:00:00
16800
2016-09-25 00:00:00
16900
2016-10-03 00:00:00
17000
2016-10-12 00:00:00
17100
2016-10-23 00:00:00
17200
2016-10-31 00:00:00
17300
2016-08-08 00:00:00
17400
2016-08-15 00:00:00
17500
2016-08-22 00:00:00
17600
2016-08-31 00:00:00
17700
2016-09-06 00:00:00
17800
2016-09-11 00:00:00
17900
2016-09-16 00:00:00
18000
2016-09-21 00:00:00
18100
2016-09-27 00:00:00
18200
2016-08-01 00:00:00
18300
2016-08-02 00:00:00
18400
2016-08-03 00:00:00
18500
2016-08-04 00:00:00
18600
2016-08-06 00:00:00
18700
2016-08-07 00:00:00
18800
2016-08-08 00:00:00
18900
2016-08-10 00:00:00
19000
2016-08-11 00:00:00
19100
2016-08-12 00:00:00
19200
2016-08-13 00:00:00
19300
2016-08-15 00:00:00
19400
2016-08-16 00:00:00
19500
2016-08-18 00:00:00
19600
2016-08-19 00:00:00
19700
2016-08-20 00:00:00
19800
2016-08-22 00:00:00
19900
2016-08-23 00:00:00
20000
2016-08-25 00:00:00
20100
2016-08-26 00:00:00
20200
2016-08-27 00:00:00
20300
2016-08-29 00:00:00
20400
2016-08-30 00:00:00
20500
2016-08-31 00:00:00
20600
2016-09-01 00:00:00
20700
2016-09-03 00:00:00
20800
2016-09-04 00:00:00
20900
2016-09-05 00:00:00
21000
2016-09-07 00:00:00
21100
2016-09-08 00:00:00
21200
2016-09-09 00:00:00
21300
2016-09-10 00:00:00
21400
2016-09-12 00:00:00
21500
2016-09-13 00:00:00
21600
2016-09-14 00:00:00
21700
2016-09-15 00:00:00
21800
2016-09-17 00:00:00
21900
2016-09-19 00:00:00
22000
2016-09-20 00:00:00
22100
2016-09-21 00:00:00
22200
2016-09-22 00:00:00
22300
2016-09-23 00:00:00
22400
2016-09-25 00:00:00
22500
2016-09-26 00:00:00
22600
2016-09-27 00:00:00
22700
2016-09-28 00:00:00
22800
2016-09-29 00:00:00
22900
2016-09-30 00:00:00
23000
2016-10-02 00:00:00
23100
2016-10-03 00:00:00
23200
2016-10-05 00:00:00
23300
2016-10-06 00:00:00
23400
2016-10-07 00:00:00
23500
2016-10-08 00:00:00
23600
2016-10-10 00:00:00
23700
2016-10-11 00:00:00
23800
2016-10-12 00:00:00
23900
2016-10-13 00:00:00
24000
2016-10-14 00:00:00
24100
2016-10-15 00:00:00
24200
2016-10-17 00:00:00
24300
2016-10-18 00:00:00
24400
2016-10-19 00:00:00
24500
2016-10-20 00:00:00
24600
2016-10-21 00:00:00
24700
2016-10-22 00:00:00
24800
2016-10-23 00:00:00
24900
2016-10-24 00:00:00
25000
2016-10-25 00:00:00
25100
2016-10-26 00:00:00
25200
2016-10-28 00:00:00
25300
2016-10-29 00:00:00
25400
2016-10-30 00:00:00
25500
2016-10-31 00:00:00
25600
2016-08-02 10:57:42
25700
2016-08-05 16:11:05
25800
2016-08-09 11:50:00
25900
2016-08-12 10:45:26
26000
2016-08-15 16:16:51
26100
2016-08-18 11:17:19
26200
2016-08-22 14:41:00
26300
2016-08-25 09:34:45
26400
2016-08-29 06:02:17
26500
2016-09-02 10:45:28
26600
2016-09-06 18:37:16
26700
2016-09-12 11:42:00
26800
2016-09-16 14:27:31
26900
01/08/2016 05:59:00 a.m.
27000
05/08/2016 03:56:00 p.m.
27100
09/08/2016 08:41:00 p.m.
27200
13/08/2016 07:49:00 p.m.
27300
18/08/2016 04:06:00 p.m.
27400
23/08/2016 07:51:00 a.m.
27500
27/08/2016 01:15:00 a.m.
27600
01/09/2016 08:31:00 a.m.
27700
05/09/2016 11:10:00 p.m.
27800
09/09/2016 09:55:00 p.m.
27900
14/09/2016 01:28:00 p.m.
28000
20/09/2016 10:11:00 a.m.
28100
24/09/2016 12:52:00 a.m.
28200
28/09/2016 07:52:00 a.m.
28300
03/10/2016 12:00:00 a.m.
28400
07/10/2016 01:57:00 p.m.
28500
11/10/2016 06:03:00 p.m.
28600
16/10/2016 02:43:00 p.m.
28700
19/10/2016 10:46:00 a.m.
28800
24/10/2016 03:51:00 p.m.
28900
27/10/2016 04:06:00 p.m.
29000
2016-08-11 00:00:00
29100
2016-08-23 00:00:00
29200
2016-09-02 00:00:00
29300
2016-09-13 00:00:00
29400
2016-09-24 00:00:00
29500
2016-10-05 00:00:00
29600
2016-10-17 00:00:00
29700
2016-11-03 00:00:00
29800
2016-11-10 00:00:00
29900
2016-11-17 00:00:00
30000
2016-11-24 00:00:00
30100
2016-12-01 00:00:00
30200
2016-12-07 00:00:00
30300
2016-12-13 00:00:00
30400
2016-12-20 00:00:00
30500
2016-12-28 00:00:00
30600
2017-01-08 00:00:00
30700
2017-01-15 00:00:00
30800
2017-01-22 00:00:00
30900
2017-01-28 00:00:00
31000
2017-01-21 00:00:00
31100
2017-01-30 00:00:00
31200
42698
31300
42707
31400
42715
31500
42722
31600
42732
31700
42742
31800
42755
31900
42764
32000
2016-11-06 00:00:00
32100
2016-11-18 00:00:00
32200
2016-11-26 00:00:00
32300
2016-12-07 00:00:00
32400
2016-12-17 00:00:00
32500
2016-12-28 00:00:00
32600
2017-01-11 00:00:00
32700
2017-01-21 00:00:00
32800
2016-11-02 00:00:00
32900
2016-11-27 00:00:00
33000
2016-12-23 00:00:00
33100
2017-01-21 00:00:00
33200
2016-11-03 07:36:00
33300
2016-11-06 06:07:35
33400
2016-11-10 07:50:43
33500
2016-11-14 07:34:59
33600
2016-11-16 18:36:28
33700
2016-11-19 16:44:49
33800
2016-11-23 21:14:06
33900
2016-11-28 08:09:41
34000
2016-12-01 10:00:41
34100
2016-12-04 10:25:37
34200
2016-12-07 23:55:43
34300
2016-12-11 06:45:54
34400
2016-12-14 15:35:51
34500
2016-12-16 21:40:32
34600
2016-12-20 20:35:47
34700
2016-12-25 18:41:34
34800
2017-01-12 15:48:14
34900
2017-01-07 16:58:07
35000
2017-01-04 09:43:59
35100
2016-11-02 00:00:00
35200
2016-11-06 00:00:00
35300
2016-11-09 00:00:00
35400
2016-11-13 00:00:00
35500
2016-11-17 00:00:00
35600
2016-11-22 00:00:00
35700
2016-11-26 00:00:00
35800
2016-11-30 00:00:00
35900
2016-12-03 00:00:00
36000
2016-12-07 00:00:00
36100
2016-12-09 00:00:00
36200
2016-12-13 00:00:00
36300
2016-12-16 00:00:00
36400
2016-12-21 00:00:00
36500
2016-12-29 00:00:00
36600
2017-01-05 00:00:00
36700
2017-01-10 00:00:00
36800
2017-01-15 00:00:00
36900
2017-01-20 00:00:00
37000
2017-01-24 00:00:00
37100
2017-01-26 00:00:00
37200
2016-11-01 00:00:00
37300
2016-11-10 00:00:00
37400
2016-11-17 00:00:00
37500
2016-11-28 00:00:00
37600
2016-12-07 00:00:00
37700
2016-12-15 00:00:00
37800
2016-12-22 00:00:00
37900
2017-01-02 00:00:00
38000
2017-01-13 00:00:00
38100
2017-01-21 00:00:00
38200
2017-02-06 00:00:00
38300
2017-02-14 00:00:00
38400
2017-02-19 00:00:00
38500
2017-02-28 00:00:00
38600
2017-03-07 00:00:00
38700
2017-03-16 00:00:00
38800
2017-03-24 00:00:00
38900
2017-04-03 00:00:00
39000
2017-04-23 00:00:00
39100
2017-04-25 00:00:00
39200
2017-02-03 00:00:00
39300
2017-02-12 00:00:00
39400
2017-02-22 00:00:00
39500
2017-03-02 00:00:00
39600
2017-03-09 00:00:00
39700
2017-03-16 00:00:00
39800
2017-03-26 00:00:00
39900
2017-04-05 00:00:00
40000
2017-04-19 00:00:00
40100
2017-04-29 00:00:00
40200
2017-02-09 00:00:00
40300
2017-02-17 00:00:00
40400
2017-02-24 00:00:00
40500
2017-03-03 00:00:00
40600
2017-03-12 00:00:00
40700
2017-03-19 00:00:00
40800
2017-03-28 00:00:00
40900
2017-04-08 00:00:00
41000
2017-04-18 00:00:00
41100
2017-04-28 00:00:00
41200
2017-02-03 00:00:00
41300
2017-02-08 00:00:00
41400
2017-02-13 00:00:00
41500
2017-02-20 00:00:00
41600
2017-02-26 00:00:00
41700
2017-03-04 00:00:00
41800
2017-03-09 00:00:00
41900
2017-03-15 00:00:00
42000
2017-03-21 00:00:00
42100
2017-03-27 00:00:00
42200
2017-04-01 00:00:00
42300
2017-04-07 00:00:00
42400
2017-04-13 00:00:00
42500
2017-04-21 00:00:00
42600
2017-04-28 00:00:00
42700
2017-02-01 00:00:00
42800
2017-02-02 00:00:00
42900
2017-02-03 00:00:00
43000
2017-02-04 00:00:00
43100
2017-02-07 00:00:00
43200
2017-02-08 00:00:00
43300
2017-02-09 00:00:00
43400
2017-02-10 00:00:00
43500
2017-02-11 00:00:00
43600
2017-02-13 00:00:00
43700
2017-02-14 00:00:00
43800
2017-02-16 00:00:00
43900
2017-02-17 00:00:00
44000
2017-02-18 00:00:00
44100
2017-02-20 00:00:00
44200
2017-02-21 00:00:00
44300
2017-02-22 00:00:00
44400
2017-02-23 00:00:00
44500
2017-02-24 00:00:00
44600
2017-02-25 00:00:00
44700
2017-02-27 00:00:00
44800
2017-02-28 00:00:00
44900
2017-03-01 00:00:00
45000
2017-03-03 00:00:00
45100
2017-03-04 00:00:00
45200
2017-03-04 00:00:00
45300
2017-03-06 00:00:00
45400
2017-03-07 00:00:00
45500
2017-03-09 00:00:00
45600
2017-03-10 00:00:00
45700
2017-03-12 00:00:00
45800
2017-03-13 00:00:00
45900
2017-03-15 00:00:00
46000
2017-03-16 00:00:00
46100
2017-03-17 00:00:00
46200
2017-03-19 00:00:00
46300
2017-03-21 00:00:00
46400
2017-03-22 00:00:00
46500
2017-03-23 00:00:00
46600
2017-03-24 00:00:00
46700
2017-03-25 00:00:00
46800
2017-03-27 00:00:00
46900
2017-03-28 00:00:00
47000
2017-03-29 00:00:00
47100
2017-03-30 00:00:00
47200
2017-03-31 00:00:00
47300
2017-04-01 00:00:00
47400
2017-04-01 00:00:00
47500
2017-04-03 00:00:00
47600
2017-04-04 00:00:00
47700
2017-04-05 00:00:00
47800
2017-04-06 00:00:00
47900
2017-04-08 00:00:00
48000
2017-04-09 00:00:00
48100
2017-04-11 00:00:00
48200
2017-04-12 00:00:00
48300
2017-04-15 00:00:00
48400
2017-04-17 00:00:00
48500
2017-04-19 00:00:00
48600
2017-04-21 00:00:00
48700
2017-04-22 00:00:00
48800
2017-04-23 00:00:00
48900
2017-04-25 00:00:00
49000
2017-04-26 00:00:00
49100
2017-04-27 00:00:00
49200
2017-04-28 00:00:00
49300
2017-04-29 00:00:00
49400
2017-04-30 00:00:00
49500
2017-02-08 00:00:00
49600
2017-02-15 00:00:00
49700
2017-02-22 00:00:00
49800
2017-03-02 00:00:00
49900
2017-03-10 00:00:00
50000
2017-03-17 00:00:00
50100
2017-03-27 00:00:00
50200
2017-04-04 00:00:00
50300
2017-04-13 00:00:00
50400
2017-04-24 00:00:00
50500
2017-04-30 00:00:00
50600
2017-02-09 00:00:00
50700
2017-02-14 00:00:00
50800
2017-02-20 00:00:00
50900
2017-02-24 00:00:00
51000
2017-02-28 00:00:00
51100
2017-03-03 00:00:00
51200
2017-03-08 00:00:00
51300
2017-02-05 00:00:00
51400
2017-02-19 00:00:00
51500
2017-03-14 00:00:00
51600
2017-03-18 00:00:00
51700
2017-03-22 00:00:00
51800
2017-03-25 00:00:00
51900
2017-03-29 00:00:00
52000
2017-04-01 00:00:00
52100
2017-04-05 00:00:00
52200
2017-04-08 00:00:00
52300
2017-04-13 00:00:00
52400
2017-04-19 00:00:00
52500
2017-04-24 00:00:00
52600
2017-04-27 00:00:00
52700
2017-02-01 00:00:00
52800
2017-02-04 00:00:00
52900
2017-02-09 00:00:00
53000
2017-02-14 00:00:00
53100
2017-02-17 00:00:00
53200
2017-02-21 00:00:00
53300
2017-02-23 00:00:00
53400
2017-02-27 00:00:00
53500
2017-03-02 00:00:00
53600
2017-03-06 00:00:00
53700
2017-03-09 00:00:00
53800
2017-03-14 00:00:00
53900
2017-03-17 00:00:00
54000
2017-03-22 00:00:00
54100
2017-03-25 00:00:00
54200
2017-03-29 00:00:00
54300
2017-04-01 00:00:00
54400
2017-04-05 00:00:00
54500
2017-04-08 00:00:00
54600
2017-04-18 00:00:00
54700
2017-04-22 00:00:00
54800
2017-04-26 00:00:00
54900
2017-04-29 00:00:00
55000

In [9]:
import pickle

In [10]:
pickle.dump(data, open("data.pickle","wb"))

In [11]:
percances = []
for ciudad in data["Ciudad"].unique():
    ciudad_obj = {"Ciudad":ciudad}
    data_ciudad = data[data["Ciudad"] == ciudad]
    counts_ciudad = data_ciudad["Mes"].value_counts()
    for mes in counts_ciudad.keys():
        ciudad_obj[mes] = counts_ciudad[mes]
    percances.append(ciudad_obj)

In [12]:
percances_df = pd.DataFrame(percances)

In [15]:
data["Número total de muertos"] = pd.to_numeric(data["Número total de muertos"])
data["Número  total de lesionados"] = pd.to_numeric(data["Número  total de lesionados"])

In [16]:
data["Número total de muertos"].sum()

68.0

In [25]:
muertes = []
for ciudad in data["Ciudad"].unique():
    ciudad_obj = {"Ciudad":ciudad}
    data_ciudad = data[data["Ciudad"] == ciudad]
    counts_ciudad = data_ciudad["Mes"].value_counts()
    for mes in counts_ciudad.keys():
        ciudad_obj[mes] = data_ciudad[data_ciudad["Mes"]==mes]["Número total de muertos"].sum()
    muertes.append(ciudad_obj)

In [26]:
lesionados = []
for ciudad in data["Ciudad"].unique():
    ciudad_obj = {"Ciudad":ciudad}
    data_ciudad = data[data["Ciudad"] == ciudad]
    counts_ciudad = data_ciudad["Mes"].value_counts()
    for mes in counts_ciudad.keys():
        ciudad_obj[mes] = data_ciudad[data_ciudad["Mes"]==mes]["Número  total de lesionados"].sum()
    lesionados.append(ciudad_obj)

In [27]:
lesionados_df = pd.DataFrame(lesionados)

In [28]:
muertes_df = pd.DataFrame(muertes)

In [29]:
np.sum(muertes_df)

Ciudad        monterreysan nicolasguadalupeapodacaescobedosa...
abril                                                        12
agosto                                                        7
diciembre                                                     5
enero                                                         2
febrero                                                       8
julio                                                         2
junio                                                         3
marzo                                                        14
mayo                                                          5
noviembre                                                     2
octubre                                                       4
septiembre                                                    4
dtype: object

In [30]:
len(data)

55013

In [39]:
percances_df.to_excel("Agregado/percances.xls")

In [40]:
muertes_df.to_excel("Agregado/muertes.xls")

In [41]:
lesionados_df.to_excel("Agregado/lesionados.xls")